In [56]:
import pandas as pd
import numpy as np


###Load train and test set
train_set = pd.read_csv(r'..\data\solubility_water\unique_train_water_final.csv')  
test_set = pd.read_csv(r'..\data\solubility_water\unique_test_water_final.csv')

solute_list = pd.concat((train_set, test_set)).reset_index(drop=True)
solute_list

,InChIKey,smiles_canon,LogS,occurence
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,O=C1c2ccccc2C(=O)c2c(Cl)cccc21,-5.54000,1.0
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,NC(N)=NS(=O)(=O)c1ccc(N)cc1,-1.98497,1.0
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1,-3.91200,1.0
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21,-3.65600,1.0
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C=Cc2ccccc2C1=NO,-2.93700,1.0
...,...,...,...,...
19214,RFZHJHSNHYIRNE-UHFFFAOYSA-N,CCC(C)(O)C(C)C,-1.03500,2.0
19215,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,-2.93000,2.0
19216,RKUNBYITZUJHSG-UHFFFAOYSA-N,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,-2.01500,2.0
19217,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,-6.23500,2.0
19218,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,-4.59500,2.0

In [57]:
solute_id = ['solute_'+str(i) for i in range(len(solute_list))]
solute_id

['solute_0',
 'solute_1',
 'solute_2',
 'solute_3',
 'solute_4',
 'solute_5',
 'solute_6',
 'solute_7',
 'solute_8',
 'solute_9',
 'solute_10',
 'solute_11',
 'solute_12',
 'solute_13',
 'solute_14',
 'solute_15',
 'solute_16',
 'solute_17',
 'solute_18',
 'solute_19',
 'solute_20',
 'solute_21',
 'solute_22',
 'solute_23',
 'solute_24',
 'solute_25',
 'solute_26',
 'solute_27',
 'solute_28',
 'solute_29',
 'solute_30',
 'solute_31',
 'solute_32',
 'solute_33',
 'solute_34',
 'solute_35',
 'solute_36',
 'solute_37',
 'solute_38',
 'solute_39',
 'solute_40',
 'solute_41',
 'solute_42',
 'solute_43',
 'solute_44',
 'solute_45',
 'solute_46',
 'solute_47',
 'solute_48',
 'solute_49',
 'solute_50',
 'solute_51',
 'solute_52',
 'solute_53',
 'solute_54',
 'solute_55',
 'solute_56',
 'solute_57',
 'solute_58',
 'solute_59',
 'solute_60',
 'solute_61',
 'solute_62',
 'solute_63',
 'solute_64',
 'solute_65',
 'solute_66',
 'solute_67',
 'solute_68',
 'solute_69',
 'solute_70',
 'solute_71',
 'solute_72',
 'solute_73',
 'solute_74',
 'solute_75',
 'solute_76',
 'solute_77',
 'solute_78',
 'solute_79',
 'solute_80',
 'solute_81',
 'solute_82',
 'solute_83',
 'solute_84',
 'solute_85',
 'solute_86',
 'solute_87',
 'solute_88',
 'solute_89',
 'solute_90',
 'solute_91',
 'solute_92',
 'solute_93',
 'solute_94',
 'solute_95',
 'solute_96',
 'solute_97',
 'solute_98',
 'solute_99',
 'solute_100',
 'solute_101',
 'solute_102',
 'solute_103',
 'solute_104',
 'solute_105',
 'solute_106',
 'solute_107',
 'solute_108',
 'solute_109',
 'solute_110',
 'solute_111',
 'solute_112',
 'solute_113',
 'solute_114',
 'solute_115',
 'solute_116',
 'solute_117',
 'solute_118',
 'solute_119',
 'solute_120',
 'solute_121',
 'solute_122',
 'solute_123',
 'solute_124',
 'solute_125',
 'solute_126',
 'solute_127',
 'solute_128',
 'solute_129',
 'solute_130',
 'solute_131',
 'solute_132',
 'solute_133',
 'solute_134',
 'solute_135',
 'solute_136',
 'solute_137',
 'solute_138',
 'solute_139',
 'solute_140',
 'solute_141',
 'solute_142',
 'solute_143',
 'solute_144',
 'solute_145',
 'solute_146',
 'solute_147',
 'solute_148',
 'solute_149',
 'solute_150',
 'solute_151',
 'solute_152',
 'solute_153',
 'solute_154',
 'solute_155',
 'solute_156',
 'solute_157',
 'solute_158',
 'solute_159',
 'solute_160',
 'solute_161',
 'solute_162',
 'solute_163',
 'solute_164',
 'solute_165',
 'solute_166',
 'solute_167',
 'solute_168',
 'solute_169',
 'solute_170',
 'solute_171',
 'solute_172',
 'solute_173',
 'solute_174',
 'solute_175',
 'solute_176',
 'solute_177',
 'solute_178',
 'solute_179',
 'solute_180',
 'solute_181',
 'solute_182',
 'solute_183',
 'solute_184',
 'solute_185',
 'solute_186',
 'solute_187',
 'solute_188',
 'solute_189',
 'solute_190',
 'solute_191',
 'solute_192',
 'solute_193',
 'solute_194',
 'solute_195',
 'solute_196',
 'solute_197',
 'solute_198',
 'solute_199',
 'solute_200',
 'solute_201',
 'solute_202',
 'solute_203',
 'solute_204',
 'solute_205',
 'solute_206',
 'solute_207',
 'solute_208',
 'solute_209',
 'solute_210',
 'solute_211',
 'solute_212',
 'solute_213',
 'solute_214',
 'solute_215',
 'solute_216',
 'solute_217',
 'solute_218',
 'solute_219',
 'solute_220',
 'solute_221',
 'solute_222',
 'solute_223',
 'solute_224',
 'solute_225',
 'solute_226',
 'solute_227',
 'solute_228',
 'solute_229',
 'solute_230',
 'solute_231',
 'solute_232',
 'solute_233',
 'solute_234',
 'solute_235',
 'solute_236',
 'solute_237',
 'solute_238',
 'solute_239',
 'solute_240',
 'solute_241',
 'solute_242',
 'solute_243',
 'solute_244',
 'solute_245',
 'solute_246',
 'solute_247',
 'solute_248',
 'solute_249',
 'solute_250',
 'solute_251',
 'solute_252',
 'solute_253',
 'solute_254',
 'solute_255',
 'solute_256',
 'solute_257',
 'solute_258',
 'solute_259',
 'solute_260',
 'solute_261',
 'solute_262',
 'solute_263',
 'solute_264',
 'solute_265',
 'solute_266',
 'solute_267',
 'solute_268',
 'solute_269',
 'solute_270',
 'solute_271',
 'solute_272',
 'solute_273',
 'solute_274',
 'solute_275',
 'solute_276',
 'solute_277',
 'solute_278',
 'solute_279',
 'solute_280',
 'solute_281',
 'solute_282',
 'solute_283',
 'solute_284',
 'solute_285',
 'solute_286',
 'solute_287',
 'solute_288',
 'solute_289',
 'solute_290',
 'solute_291',
 'solute_292',
 'solute_293',
 'solute_294',
 'solute_295',
 'solute_296',
 'solute_297',
 'solute_298',
 'solute_299',
 'solute_300',
 'solute_301',
 'solute_302',
 'solute_303',
 'solute_304',
 'solute_305',
 'solute_306',
 'solute_307',
 'solute_308',
 'solute_309',
 'solute_310',
 'solute_311',
 'solute_312',
 'solute_313',
 'solute_314',
 'solute_315',
 'solute_316',
 'solute_317',
 'solute_318',
 'solute_319',
 'solute_320',
 'solute_321',
 'solute_322',
 'solute_323',
 'solute_324',
 'solute_325',
 'solute_326',
 'solute_327',
 'solute_328',
 'solute_329',
 'solute_330',
 'solute_331',
 'solute_332',
 'solute_333',
 'solute_334',
 'solute_335',
 'solute_336',
 'solute_337',
 'solute_338',
 'solute_339',
 'solute_340',
 'solute_341',
 'solute_342',
 'solute_343',
 'solute_344',
 'solute_345',
 'solute_346',
 'solute_347',
 'solute_348',
 'solute_349',
 'solute_350',
 'solute_351',
 'solute_352',
 'solute_353',
 'solute_354',
 'solute_355',
 'solute_356',
 'solute_357',
 'solute_358',
 'solute_359',
 'solute_360',
 'solute_361',
 'solute_362',
 'solute_363',
 'solute_364',
 'solute_365',
 'solute_366',
 'solute_367',
 'solute_368',
 'solute_369',
 'solute_370',
 'solute_371',
 'solute_372',
 'solute_373',
 'solute_374',
 'solute_375',
 'solute_376',
 'solute_377',
 'solute_378',
 'solute_379',
 'solute_380',
 'solute_381',
 'solute_382',
 'solute_383',
 'solute_384',
 'solute_385',
 'solute_386',
 'solute_387',
 'solute_388',
 'solute_389',
 'solute_390',
 'solute_391',
 'solute_392',
 'solute_393',
 'solute_394',
 'solute_395',
 'solute_396',
 'solute_397',
 'solute_398',
 'solute_399',
 'solute_400',
 'solute_401',
 'solute_402',
 'solute_403',
 'solute_404',
 'solute_405',
 'solute_406',
 'solute_407',
 'solute_408',
 'solute_409',
 'solute_410',
 'solute_411',
 'solute_412',
 'solute_413',
 'solute_414',
 'solute_415',
 'solute_416',
 'solute_417',
 'solute_418',
 'solute_419',
 'solute_420',
 'solute_421',
 'solute_422',
 'solute_423',
 'solute_424',
 'solute_425',
 'solute_426',
 'solute_427',
 'solute_428',
 'solute_429',
 'solute_430',
 'solute_431',
 'solute_432',
 'solute_433',
 'solute_434',
 'solute_435',
 'solute_436',
 'solute_437',
 'solute_438',
 'solute_439',
 'solute_440',
 'solute_441',
 'solute_442',
 'solute_443',
 'solute_444',
 'solute_445',
 'solute_446',
 'solute_447',
 'solute_448',
 'solute_449',
 'solute_450',
 'solute_451',
 'solute_452',
 'solute_453',
 'solute_454',
 'solute_455',
 'solute_456',
 'solute_457',
 'solute_458',
 'solute_459',
 'solute_460',
 'solute_461',
 'solute_462',
 'solute_463',
 'solute_464',
 'solute_465',
 'solute_466',
 'solute_467',
 'solute_468',
 'solute_469',
 'solute_470',
 'solute_471',
 'solute_472',
 'solute_473',
 'solute_474',
 'solute_475',
 'solute_476',
 'solute_477',
 'solute_478',
 'solute_479',
 'solute_480',
 'solute_481',
 'solute_482',
 'solute_483',
 'solute_484',
 'solute_485',
 'solute_486',
 'solute_487',
 'solute_488',
 'solute_489',
 'solute_490',
 'solute_491',
 'solute_492',
 'solute_493',
 'solute_494',
 'solute_495',
 'solute_496',
 'solute_497',
 'solute_498',
 'solute_499',
 'solute_500',
 'solute_501',
 'solute_502',
 'solute_503',
 'solute_504',
 'solute_505',
 'solute_506',
 'solute_507',
 'solute_508',
 'solute_509',
 'solute_510',
 'solute_511',
 'solute_512',
 'solute_513',
 'solute_514',
 'solute_515',
 'solute_516',
 'solute_517',
 'solute_518',
 'solute_519',
 'solute_520',
 'solute_521',
 'solute_522',
 'solute_523',
 'solute_524',
 'solute_525',
 'solute_526',
 'solute_527',
 'solute_528',
 'solute_529',
 'solute_530',
 'solute_531',
 'solute_532',
 'solute_533',
 'solute_534',
 'solute_535',
 'solute_536',
 'solute_537',
 'solute_538',
 'solute_539',
 'solute_540',
 'solute_541',
 'solute_542',
 'solute_543',
 'solute_544',
 'solute_545',
 'solute_546',
 'solute_547',
 'solute_548',
 'solute_549',
 'solute_550',
 'solute_551',
 'solute_552',
 'solute_553',
 'solute_554',
 'solute_555',
 'solute_556',
 'solute_557',
 'solute_558',
 'solute_559',
 'solute_560',
 'solute_561',
 'solute_562',
 'solute_563',
 'solute_564',
 'solute_565',
 'solute_566',
 'solute_567',
 'solute_568',
 'solute_569',
 'solute_570',
 'solute_571',
 'solute_572',
 'solute_573',
 'solute_574',
 'solute_575',
 'solute_576',
 'solute_577',
 'solute_578',
 'solute_579',
 'solute_580',
 'solute_581',
 'solute_582',
 'solute_583',
 'solute_584',
 'solute_585',
 'solute_586',
 'solute_587',
 'solute_588',
 'solute_589',
 'solute_590',
 'solute_591',
 'solute_592',
 'solute_593',
 'solute_594',
 'solute_595',
 'solute_596',
 'solute_597',
 'solute_598',
 'solute_599',
 'solute_600',
 'solute_601',
 'solute_602',
 'solute_603',
 'solute_604',
 'solute_605',
 'solute_606',
 'solute_607',
 'solute_608',
 'solute_609',
 'solute_610',
 'solute_611',
 'solute_612',
 'solute_613',
 'solute_614',
 'solute_615',
 'solute_616',
 'solute_617',
 'solute_618',
 'solute_619',
 'solute_620',
 'solute_621',
 'solute_622',
 'solute_623',
 'solute_624',
 'solute_625',
 'solute_626',
 'solute_627',
 'solute_628',
 'solute_629',
 'solute_630',
 'solute_631',
 'solute_632',
 'solute_633',
 'solute_634',
 'solute_635',
 'solute_636',
 'solute_637',
 'solute_638',
 'solute_639',
 'solute_640',
 'solute_641',
 'solute_642',
 'solute_643',
 'solute_644',
 'solute_645',
 'solute_646',
 'solute_647',
 'solute_648',
 'solute_649',
 'solute_650',
 'solute_651',
 'solute_652',
 'solute_653',
 'solute_654',
 'solute_655',
 'solute_656',
 'solute_657',
 'solute_658',
 'solute_659',
 'solute_660',
 'solute_661',
 'solute_662',
 'solute_663',
 'solute_664',
 'solute_665',
 'solute_666',
 'solute_667',
 'solute_668',
 'solute_669',
 'solute_670',
 'solute_671',
 'solute_672',
 'solute_673',
 'solute_674',
 'solute_675',
 'solute_676',
 'solute_677',
 'solute_678',
 'solute_679',
 'solute_680',
 'solute_681',
 'solute_682',
 'solute_683',
 'solute_684',
 'solute_685',
 'solute_686',
 'solute_687',
 'solute_688',
 'solute_689',
 'solute_690',
 'solute_691',
 'solute_692',
 'solute_693',
 'solute_694',
 'solute_695',
 'solute_696',
 'solute_697',
 'solute_698',
 'solute_699',
 'solute_700',
 'solute_701',
 'solute_702',
 'solute_703',
 'solute_704',
 'solute_705',
 'solute_706',
 'solute_707',
 'solute_708',
 'solute_709',
 'solute_710',
 'solute_711',
 'solute_712',
 'solute_713',
 'solute_714',
 'solute_715',
 'solute_716',
 'solute_717',
 'solute_718',
 'solute_719',
 'solute_720',
 'solute_721',
 'solute_722',
 'solute_723',
 'solute_724',
 'solute_725',
 'solute_726',
 'solute_727',
 'solute_728',
 'solute_729',
 'solute_730',
 'solute_731',
 'solute_732',
 'solute_733',
 'solute_734',
 'solute_735',
 'solute_736',
 'solute_737',
 'solute_738',
 'solute_739',
 'solute_740',
 'solute_741',
 'solute_742',
 'solute_743',
 'solute_744',
 'solute_745',
 'solute_746',
 'solute_747',
 'solute_748',
 'solute_749',
 'solute_750',
 'solute_751',
 'solute_752',
 'solute_753',
 'solute_754',
 'solute_755',
 'solute_756',
 'solute_757',
 'solute_758',
 'solute_759',
 'solute_760',
 'solute_761',
 'solute_762',
 'solute_763',
 'solute_764',
 'solute_765',
 'solute_766',
 'solute_767',
 'solute_768',
 'solute_769',
 'solute_770',
 'solute_771',
 'solute_772',
 'solute_773',
 'solute_774',
 'solute_775',
 'solute_776',
 'solute_777',
 'solute_778',
 'solute_779',
 'solute_780',
 'solute_781',
 'solute_782',
 'solute_783',
 'solute_784',
 'solute_785',
 'solute_786',
 'solute_787',
 'solute_788',
 'solute_789',
 'solute_790',
 'solute_791',
 'solute_792',
 'solute_793',
 'solute_794',
 'solute_795',
 'solute_796',
 'solute_797',
 'solute_798',
 'solute_799',
 'solute_800',
 'solute_801',
 'solute_802',
 'solute_803',
 'solute_804',
 'solute_805',
 'solute_806',
 'solute_807',
 'solute_808',
 'solute_809',
 'solute_810',
 'solute_811',
 'solute_812',
 'solute_813',
 'solute_814',
 'solute_815',
 'solute_816',
 'solute_817',
 'solute_818',
 'solute_819',
 'solute_820',
 'solute_821',
 'solute_822',
 'solute_823',
 'solute_824',
 'solute_825',
 'solute_826',
 'solute_827',
 'solute_828',
 'solute_829',
 'solute_830',
 'solute_831',
 'solute_832',
 'solute_833',
 'solute_834',
 'solute_835',
 'solute_836',
 'solute_837',
 'solute_838',
 'solute_839',
 'solute_840',
 'solute_841',
 'solute_842',
 'solute_843',
 'solute_844',
 'solute_845',
 'solute_846',
 'solute_847',
 'solute_848',
 'solute_849',
 'solute_850',
 'solute_851',
 'solute_852',
 'solute_853',
 'solute_854',
 'solute_855',
 'solute_856',
 'solute_857',
 'solute_858',
 'solute_859',
 'solute_860',
 'solute_861',
 'solute_862',
 'solute_863',
 'solute_864',
 'solute_865',
 'solute_866',
 'solute_867',
 'solute_868',
 'solute_869',
 'solute_870',
 'solute_871',
 'solute_872',
 'solute_873',
 'solute_874',
 'solute_875',
 'solute_876',
 'solute_877',
 'solute_878',
 'solute_879',
 'solute_880',
 'solute_881',
 'solute_882',
 'solute_883',
 'solute_884',
 'solute_885',
 'solute_886',
 'solute_887',
 'solute_888',
 'solute_889',
 'solute_890',
 'solute_891',
 'solute_892',
 'solute_893',
 'solute_894',
 'solute_895',
 'solute_896',
 'solute_897',
 'solute_898',
 'solute_899',
 'solute_900',
 'solute_901',
 'solute_902',
 'solute_903',
 'solute_904',
 'solute_905',
 'solute_906',
 'solute_907',
 'solute_908',
 'solute_909',
 'solute_910',
 'solute_911',
 'solute_912',
 'solute_913',
 'solute_914',
 'solute_915',
 'solute_916',
 'solute_917',
 'solute_918',
 'solute_919',
 'solute_920',
 'solute_921',
 'solute_922',
 'solute_923',
 'solute_924',
 'solute_925',
 'solute_926',
 'solute_927',
 'solute_928',
 'solute_929',
 'solute_930',
 'solute_931',
 'solute_932',
 'solute_933',
 'solute_934',
 'solute_935',
 'solute_936',
 'solute_937',
 'solute_938',
 'solute_939',
 'solute_940',
 'solute_941',
 'solute_942',
 'solute_943',
 'solute_944',
 'solute_945',
 'solute_946',
 'solute_947',
 'solute_948',
 'solute_949',
 'solute_950',
 'solute_951',
 'solute_952',
 'solute_953',
 'solute_954',
 'solute_955',
 'solute_956',
 'solute_957',
 'solute_958',
 'solute_959',
 'solute_960',
 'solute_961',
 'solute_962',
 'solute_963',
 'solute_964',
 'solute_965',
 'solute_966',
 'solute_967',
 'solute_968',
 'solute_969',
 'solute_970',
 'solute_971',
 'solute_972',
 'solute_973',
 'solute_974',
 'solute_975',
 'solute_976',
 'solute_977',
 'solute_978',
 'solute_979',
 'solute_980',
 'solute_981',
 'solute_982',
 'solute_983',
 'solute_984',
 'solute_985',
 'solute_986',
 'solute_987',
 'solute_988',
 'solute_989',
 'solute_990',
 'solute_991',
 'solute_992',
 'solute_993',
 'solute_994',
 'solute_995',
 'solute_996',
 'solute_997',
 'solute_998',
 'solute_999',
 ...]

In [58]:
solute_list['solute_id'] = solute_id
solute_list

,InChIKey,smiles_canon,LogS,occurence,solute_id
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,O=C1c2ccccc2C(=O)c2c(Cl)cccc21,-5.54000,1.0,solute_0
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,NC(N)=NS(=O)(=O)c1ccc(N)cc1,-1.98497,1.0,solute_1
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1,-3.91200,1.0,solute_2
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21,-3.65600,1.0,solute_3
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C=Cc2ccccc2C1=NO,-2.93700,1.0,solute_4
...,...,...,...,...,...
19214,RFZHJHSNHYIRNE-UHFFFAOYSA-N,CCC(C)(O)C(C)C,-1.03500,2.0,solute_19214
19215,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,-2.93000,2.0,solute_19215
19216,RKUNBYITZUJHSG-UHFFFAOYSA-N,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,-2.01500,2.0,solute_19216
19217,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,-6.23500,2.0,solute_19217
19218,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,-4.59500,2.0,solute_19218

In [59]:
solute_list = solute_list.drop(["LogS","occurence"], axis=1)
solute_list

,InChIKey,smiles_canon,solute_id
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,O=C1c2ccccc2C(=O)c2c(Cl)cccc21,solute_0
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,NC(N)=NS(=O)(=O)c1ccc(N)cc1,solute_1
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1,solute_2
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21,solute_3
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C=Cc2ccccc2C1=NO,solute_4
...,...,...,...
19214,RFZHJHSNHYIRNE-UHFFFAOYSA-N,CCC(C)(O)C(C)C,solute_19214
19215,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,solute_19215
19216,RKUNBYITZUJHSG-UHFFFAOYSA-N,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,solute_19216
19217,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,solute_19217
19218,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,solute_19218

In [60]:
solute_list = solute_list[['InChIKey','solute_id','smiles_canon']]
solute_list

,InChIKey,solute_id,smiles_canon
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,solute_0,O=C1c2ccccc2C(=O)c2c(Cl)cccc21
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,solute_1,NC(N)=NS(=O)(=O)c1ccc(N)cc1
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,solute_2,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,solute_3,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,solute_4,O=C1C=Cc2ccccc2C1=NO
...,...,...,...
19214,RFZHJHSNHYIRNE-UHFFFAOYSA-N,solute_19214,CCC(C)(O)C(C)C
19215,OWNAXTAAAQTBSP-UHFFFAOYSA-N,solute_19215,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1
19216,RKUNBYITZUJHSG-UHFFFAOYSA-N,solute_19216,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2
19217,DFBKLUNHFCTMDC-UHFFFAOYSA-N,solute_19217,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl
19218,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,solute_19218,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl

In [61]:
solute_list.to_csv('../data/solubility_water/solute_list.csv', index=False)

In [65]:
solvent_list = pd.read_csv(r'..\data\solvent_list.csv')
water = solvent_list.loc[solvent_list['solvent_name']=='WATER'].reset_index(drop=True)
water

  solvent_name   solvent_id smiles_can
0        WATER  solvent_844          O

In [66]:
water.to_csv('../data/solubility_water/solvent_list_water.csv', index=False)

In [69]:
water_id = water['solvent_id'].iloc[0]
water_id

'solvent_844'

In [70]:
train_set['solvent_id'] = [water_id]*len(train_set)
train_set

,InChIKey,smiles_canon,LogS,occurence,solvent_id
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,O=C1c2ccccc2C(=O)c2c(Cl)cccc21,-5.540000,1.0,solvent_844
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,NC(N)=NS(=O)(=O)c1ccc(N)cc1,-1.984970,1.0,solvent_844
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1,-3.912000,1.0,solvent_844
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21,-3.656000,1.0,solvent_844
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C=Cc2ccccc2C1=NO,-2.937000,1.0,solvent_844
...,...,...,...,...,...
17932,CTAPFRYPJLPFDF-UHFFFAOYSA-N,c1cnoc1,0.383095,2.0,solvent_844
17933,UYJUZNLFJAWNEZ-UHFFFAOYSA-N,c1coc(-c2nc3ccccc3[nH]2)c1,-3.414016,2.0,solvent_844
17934,NSPMIYGKQJPBQR-UHFFFAOYSA-N,c1nc[nH]n1,0.897170,2.0,solvent_844
17935,KDCGOANMDULRCW-UHFFFAOYSA-N,c1ncc2[nH]cnc2n1,0.619695,2.0,solvent_844
17936,GIIGHSIIKVOWKZ-UHFFFAOYSA-N,c1ncc2n[nH]nc2n1,-0.231900,2.0,solvent_844

In [73]:
train_solute_id = []
for solute in train_set['smiles_canon'].tolist():
    searched_id = solute_list[solute_list['smiles_canon'] == solute]['solute_id'].tolist()
    if len(searched_id) != 1:
        print('WARNING: conflicting id')
        break
    searched_id = searched_id[0]
    train_solute_id.append(searched_id)
train_set['solute_id'] = train_solute_id
train_set

,InChIKey,smiles_canon,LogS,occurence,solvent_id,solute_id
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,O=C1c2ccccc2C(=O)c2c(Cl)cccc21,-5.540000,1.0,solvent_844,solute_0
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,NC(N)=NS(=O)(=O)c1ccc(N)cc1,-1.984970,1.0,solvent_844,solute_1
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1,-3.912000,1.0,solvent_844,solute_2
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21,-3.656000,1.0,solvent_844,solute_3
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C=Cc2ccccc2C1=NO,-2.937000,1.0,solvent_844,solute_4
...,...,...,...,...,...,...
17932,CTAPFRYPJLPFDF-UHFFFAOYSA-N,c1cnoc1,0.383095,2.0,solvent_844,solute_17932
17933,UYJUZNLFJAWNEZ-UHFFFAOYSA-N,c1coc(-c2nc3ccccc3[nH]2)c1,-3.414016,2.0,solvent_844,solute_17933
17934,NSPMIYGKQJPBQR-UHFFFAOYSA-N,c1nc[nH]n1,0.897170,2.0,solvent_844,solute_17934
17935,KDCGOANMDULRCW-UHFFFAOYSA-N,c1ncc2[nH]cnc2n1,0.619695,2.0,solvent_844,solute_17935
17936,GIIGHSIIKVOWKZ-UHFFFAOYSA-N,c1ncc2n[nH]nc2n1,-0.231900,2.0,solvent_844,solute_17936

In [74]:
test_set['solvent_id'] = [water_id]*len(test_set)
test_solute_id = []
for solute in test_set['smiles_canon'].tolist():
    searched_id = solute_list[solute_list['smiles_canon'] == solute]['solute_id'].tolist()
    if len(searched_id) != 1:
        print('WARNING: conflicting id')
        break
    searched_id = searched_id[0]
    test_solute_id.append(searched_id)
test_set['solute_id'] = test_solute_id
test_set

,InChIKey,smiles_canon,LogS,occurence,solvent_id,solute_id
0,OFBQJSOFQDEBGM-UHFFFAOYSA-N,CCCCC,-3.180,1.0,solvent_844,solute_17937
1,RGSFGYAAUTVSQA-UHFFFAOYSA-N,C1CCCC1,-2.640,1.0,solvent_844,solute_17938
2,VLKZOEOYAKHREP-UHFFFAOYSA-N,CCCCCC,-3.840,1.0,solvent_844,solute_17939
3,AFABGHUZZDYHJO-UHFFFAOYSA-N,CCCC(C)C,-3.740,1.0,solvent_844,solute_17940
4,HNRMPXKDFBEGFZ-UHFFFAOYSA-N,CCC(C)(C)C,-3.550,1.0,solvent_844,solute_17941
...,...,...,...,...,...,...
1277,RFZHJHSNHYIRNE-UHFFFAOYSA-N,CCC(C)(O)C(C)C,-1.035,2.0,solvent_844,solute_19214
1278,OWNAXTAAAQTBSP-UHFFFAOYSA-N,CN(C)C(=O)Nc1cccc(OC(=O)NC(C)(C)C)c1,-2.930,2.0,solvent_844,solute_19215
1279,RKUNBYITZUJHSG-UHFFFAOYSA-N,CN1C2CCC1CC(OC(=O)C(CO)c1ccccc1)C2,-2.015,2.0,solvent_844,solute_19216
1280,DFBKLUNHFCTMDC-UHFFFAOYSA-N,ClC1=C(Cl)C2(Cl)C3C4CC(C5OC45)C3C1(Cl)C2(Cl)Cl,-6.235,2.0,solvent_844,solute_19217
1281,JLYXXMFPNIAWKQ-UHFFFAOYSA-N,ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl,-4.595,2.0,solvent_844,solute_19218

In [77]:
#remove conflicting smiles (RDKit cannot process them into mol object due to a Nitrogen atom having more valence than expected)
conflicting_smiles = ["CC1=CC=C[NH++]([O-])[CH-]1", "OC(=O)C1=C[NH++]([O-])[CH-]C=C1"]

indx = train_set[train_set["smiles_canon"].apply(lambda x : x in conflicting_smiles)]   
train_set = train_set.drop(index=indx.index)
train_set

,InChIKey,smiles_canon,LogS,occurence,solvent_id,solute_id
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,O=C1c2ccccc2C(=O)c2c(Cl)cccc21,-5.540000,1.0,solvent_844,solute_0
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,NC(N)=NS(=O)(=O)c1ccc(N)cc1,-1.984970,1.0,solvent_844,solute_1
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1,-3.912000,1.0,solvent_844,solute_2
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21,-3.656000,1.0,solvent_844,solute_3
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C=Cc2ccccc2C1=NO,-2.937000,1.0,solvent_844,solute_4
...,...,...,...,...,...,...
17932,CTAPFRYPJLPFDF-UHFFFAOYSA-N,c1cnoc1,0.383095,2.0,solvent_844,solute_17932
17933,UYJUZNLFJAWNEZ-UHFFFAOYSA-N,c1coc(-c2nc3ccccc3[nH]2)c1,-3.414016,2.0,solvent_844,solute_17933
17934,NSPMIYGKQJPBQR-UHFFFAOYSA-N,c1nc[nH]n1,0.897170,2.0,solvent_844,solute_17934
17935,KDCGOANMDULRCW-UHFFFAOYSA-N,c1ncc2[nH]cnc2n1,0.619695,2.0,solvent_844,solute_17935
17936,GIIGHSIIKVOWKZ-UHFFFAOYSA-N,c1ncc2n[nH]nc2n1,-0.231900,2.0,solvent_844,solute_17936

In [78]:
train_set.reset_index(drop=True)
train_set

,InChIKey,smiles_canon,LogS,occurence,solvent_id,solute_id
0,BOCJQSFSGAZAPQ-UHFFFAOYSA-N,O=C1c2ccccc2C(=O)c2c(Cl)cccc21,-5.540000,1.0,solvent_844,solute_0
1,BRBKOPJOKNSWSG-UHFFFAOYSA-N,NC(N)=NS(=O)(=O)c1ccc(N)cc1,-1.984970,1.0,solvent_844,solute_1
2,BRPOVUNVTUCYNN-UHFFFAOYSA-N,CCC1C(N)CN1c1cc2c(cc1F)c(=O)c(C(=O)O)cn2C1CC1,-3.912000,1.0,solvent_844,solute_2
3,BWXSXZAIQQSFPW-UHFFFAOYSA-N,CCC1(CC)OC(=O)c2cc([N+](=O)[O-])ccc21,-3.656000,1.0,solvent_844,solute_3
4,CAQHPYSDQFDJAL-UHFFFAOYSA-N,O=C1C=Cc2ccccc2C1=NO,-2.937000,1.0,solvent_844,solute_4
...,...,...,...,...,...,...
17932,CTAPFRYPJLPFDF-UHFFFAOYSA-N,c1cnoc1,0.383095,2.0,solvent_844,solute_17932
17933,UYJUZNLFJAWNEZ-UHFFFAOYSA-N,c1coc(-c2nc3ccccc3[nH]2)c1,-3.414016,2.0,solvent_844,solute_17933
17934,NSPMIYGKQJPBQR-UHFFFAOYSA-N,c1nc[nH]n1,0.897170,2.0,solvent_844,solute_17934
17935,KDCGOANMDULRCW-UHFFFAOYSA-N,c1ncc2[nH]cnc2n1,0.619695,2.0,solvent_844,solute_17935
17936,GIIGHSIIKVOWKZ-UHFFFAOYSA-N,c1ncc2n[nH]nc2n1,-0.231900,2.0,solvent_844,solute_17936

In [79]:
train_set.to_csv('../data/solubility_water/COMPATIBLE_unique_train_water_final.csv', index=False)
test_set.to_csv('../data/solubility_water/COMPATIBLE_unique_test_water_final.csv', index=False)